apiVersion: v1
kind: Pod
metadata:
  labels:
    name: webapp-color
  name: webapp-color
spec:
  containers:
    - name : webapp-color
      image: nginx
      env:
        - name: APP_COLOR
          value: green